### ISSUE TITLE
Move specific URL to env files

### ISSUE THREAD

**Issue by davidjguru** [davidjguru/summerhouse#1]
Pass specific URLs to environment variables available in .env custom files. 
I mean, instead of (config.yaml): 

```hooks:
  pre-start:
    - exec-host: "wget https://raw.githubusercontent.com/drud/ddev-contrib/master/docker-compose-services/portainer/docker-compose.portainer.yaml"
```

Load URL in .env file.

**Comment by saganakat** [comment]
The documentation proposes [two ways to load environment variables](https://ddev.readthedocs.io/en/stable/users/extend/customization-extendibility/#providing-custom-environment-variables-to-a-container).

On the one hand, in the config.yml file with the web_environment parameter. 
On the other side create a new partial docker_compose.yaml.

Do you have a concrete structure in mind for the second option? Like ,...

```bash
.
├── .ddev/
│   ├── config.yaml
├── env/
│   ├── docker-compose.env-file.yaml
│   ├── .env
├── ...
```

**Comment by davidjguru** [comment]
Hi @saganakat I think we can use the second one, It can be more "ortodox", IMHO.

**Comment by davidjguru** [comment]
Will not be addressed, Won't fix.
